const mongoose = require('mongoose');

// The Task model now doubles as a generic "Session" so the existing task
// APIs, Dashboard, and Tasks page keep working unchanged, while the new
// planner features (study/notes/practice/revision/mock exam/custom) all
// reuse the same collection instead of a parallel one.
const SESSION_TYPES = ['study', 'notes', 'practice', 'revision', 'mock_exam', 'custom'];
const STATUS_VALUES = ['not_started', 'in_progress', 'completed'];

const taskSchema = new mongoose.Schema(
  {
    user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, index: true },
    subject: { type: String, required: true, trim: true },
    title: { type: String, required: true, trim: true },
    notes: { type: String, trim: true, default: '' }, // also used as "description" for custom tasks
    date: { type: Date, required: true }, // day this task is scheduled for
    durationMinutes: { type: Number, required: true, min: 5, default: 30 },
    priority: { type: Number, min: 1, max: 5, default: 3 },
    completed: { type: Boolean, default: false }, // kept for backward compatibility
    completedAt: { type: Date },
    source: { type: String, enum: ['ai', 'manual'], default: 'manual' },

    // --- New fields for the flexible daily planner ---
    type: { type: String, enum: SESSION_TYPES, default: 'study', index: true },
    subtopic: { type: String, trim: true, default: '' },
    startTime: { type: String, default: '' }, // "HH:mm", 24h, empty for legacy/undated tasks
    endTime: { type: String, default: '' }, // "HH:mm"
    status: { type: String, enum: STATUS_VALUES, default: 'not_started' },
    order: { type: Number, default: 0 }, // manual drag-and-drop order within a day

    // Links back to the feature that auto-generated this session, so
    // regenerating/deleting a plan only touches sessions it created.
    linkedSessionId: { type: mongoose.Schema.Types.ObjectId, ref: 'Task', default: null }, // e.g. notes -> its study session
    revisionPlanId: { type: mongoose.Schema.Types.ObjectId, ref: 'RevisionPlan', default: null },
    mockExamId: { type: mongoose.Schema.Types.ObjectId, ref: 'MockExam', default: null },
    autoGenerated: { type: Boolean, default: false },

    // Links a revision session back to the chapter that spawned it (see
    // utils/chapterRevision.js), so completing it can bump the chapter's
    // revisionCount and so "upcoming/missed revisions" can be queried directly.
    subjectId: { type: mongoose.Schema.Types.ObjectId, ref: 'Subject', default: null },
    chapterId: { type: mongoose.Schema.Types.ObjectId, default: null }, // subdocument _id of the chapter within Subject.subtopics
    revisionStage: { type: String, default: '' }, // e.g. 'Day 1', 'Day 7', 'Before Exam'
  },
  { timestamps: true }
);

taskSchema.index({ user: 1, date: 1 });
taskSchema.index({ user: 1, date: 1, order: 1 });

// Keep `completed` and `status` in sync no matter which one the client sets,
// so old clients (using the boolean) and new UI (using the enum) agree.
taskSchema.pre('save', function syncCompletedAndStatus(next) {
  if (this.isModified('completed') && !this.isModified('status')) {
    this.status = this.completed ? 'completed' : this.status === 'completed' ? 'not_started' : this.status;
  } else if (this.isModified('status')) {
    this.completed = this.status === 'completed';
  }
  next();
});

module.exports = mongoose.model('Task', taskSchema);
module.exports.SESSION_TYPES = SESSION_TYPES;
module.exports.STATUS_VALUES = STATUS_VALUES;

