// AI Planner — Natural Language + Voice study-plan generation.
//
// This feature is an ADDITIVE layer on top of the app's existing planning
// engine — it does not replace or duplicate any logic. It:
//   1. Parses the user's free-text/voice plan (utils/nlpPlanParser.js).
//   2. Maps the result onto the SAME User preference fields and Subject
//      documents every other page already reads/writes.
//   3. Calls the SAME regenerateFutureSchedule() ("Dynamic Synchronization
//      Engine") used by subjectController/plannerLifecycleController, so
//      Dashboard, Timeline, Calendar, Schedule, Tasks, Analytics, Mock
//      Exams, and Revision all update the exact same way they would if the
//      user had built the plan by hand.
//
// /generate performs NO database writes — it's a pure preview so the user
// can review/edit before anything is created (per the "Safety" requirement:
// show preview, highlight conflicts, ask for confirmation).
// /confirm performs the actual writes, re-using existing controllers'
// create/update logic patterns so behavior stays consistent app-wide.

const Subject = require('../models/Subject');
const Task = require('../models/Task');
const RevisionPlan = require('../models/RevisionPlan');
const MockExam = require('../models/MockExam');
const { parseStudyPlanText, matchPresetSubjectName } = require('../utils/nlpPlanParser');
const { GATE_CSE_SUBJECTS } = require('../utils/gateCsePreset');
const { computePlannerMetrics, autoGenerateDeadlines } = require('../utils/deadlinePlanner');
const { regenerateFutureSchedule } = require('../utils/scheduleRebalancer');
const { checkDeadlineFeasible } = require('../utils/scheduleValidation');
const { generateRevisionSessions } = require('../utils/sessionGenerator');

const DEFAULT_SUBJECT_ESTIMATED_HOURS = 30;

/** Builds the chapter/subtopic list for a subject in the preview/confirm payload — from the GATE preset if matched, otherwise one placeholder chapter. */
function buildSubtopics(parsedSubject) {
  if (parsedSubject.matchedPreset) {
    const preset = GATE_CSE_SUBJECTS.find((s) => s.name === parsedSubject.matchedPreset);
    if (preset) {
      return preset.subtopics.map((c) => ({ ...c, status: 'not_started' }));
    }
  }
  return [
    {
      name: `${parsedSubject.name} — Full Syllabus`,
      status: 'not_started',
      estimatedHours: DEFAULT_SUBJECT_ESTIMATED_HOURS,
      importance: parsedSubject.prioritized ? 5 : 3,
      difficulty: parsedSubject.difficulty || 3,
      pyqWeightage: 0,
    },
  ];
}

function estimatedHoursFor(parsedSubject, subtopics) {
  if (parsedSubject.matchedPreset) {
    const preset = GATE_CSE_SUBJECTS.find((s) => s.name === parsedSubject.matchedPreset);
    if (preset) return subtopics.reduce((sum, c) => sum + (c.estimatedHours || 0), 0);
  }
  return DEFAULT_SUBJECT_ESTIMATED_HOURS;
}

/**
 * Shared builder: turns a parsed NLU result into the full preview payload
 * (user-field changes + subject drafts + warnings/conflicts), without
 * touching the database. Used by both /generate and, as a sanity re-check,
 * by /confirm.
 */
function buildPreview(user, parsed) {
  const now = new Date();
  const warnings = [...parsed.warnings];

  const examDate = parsed.examDate || user.examDate || null;
  const hoursPerDay = parsed.hoursPerDay || user.hoursPerDay || 4;
  const weeklyOffDay = parsed.weeklyOffDay !== null ? parsed.weeklyOffDay : user.weeklyOffDay;
  const bufferDays = parsed.bufferDays !== null ? parsed.bufferDays : user.bufferDays;

  if (parsed.examDateApproximate) {
    warnings.push(`Exam date "${examDate ? examDate.toDateString() : ''}" was approximated from a month/year — please confirm the exact date.`);
  }

  const subjectDrafts = parsed.subjects.map((s) => {
    const subtopics = buildSubtopics(s);
    const estimatedHours = estimatedHoursFor(s, subtopics);
    const deadlineWarning =
      s.completionDeadline && examDate ? checkDeadlineFeasible(s.completionDeadline, examDate) : null;
    if (deadlineWarning) warnings.push(deadlineWarning);

    return {
      name: s.name,
      matchedPreset: s.matchedPreset,
      priority: s.priority,
      difficulty: s.difficulty,
      weak: Boolean(s.weak),
      strong: Boolean(s.strong),
      prioritized: Boolean(s.prioritized),
      completionDeadline: s.completionDeadline,
      estimatedHours,
      subtopics,
      isNewSubject: true, // refined against the DB in generatePlanPreview() below
    };
  });

  // Rough daily-hours feasibility check across all drafted subjects.
  const totalHours = subjectDrafts.reduce((sum, s) => sum + s.estimatedHours, 0);
  if (examDate) {
    const days = Math.max(1, Math.round((examDate - now) / (1000 * 60 * 60 * 24)));
    const studyDays = weeklyOffDay !== null && weeklyOffDay !== undefined ? Math.round((days * 6) / 7) : days;
    const requiredDailyHours = studyDays > 0 ? Math.round((totalHours / studyDays) * 100) / 100 : totalHours;
    if (requiredDailyHours > hoursPerDay) {
      warnings.push(
        `This plan needs about ${requiredDailyHours}h/day to finish everything before the exam, but only ${hoursPerDay}h/day is available. Consider extending some deadlines or increasing daily hours.`
      );
    }
  }

  const mockPlan = parsed.mockTestsPerMonth
    ? {
        perMonth: parsed.mockTestsPerMonth,
        // The app's recurring Mock Exam feature is weekly-based, so a
        // "N per month" request is approximated as a weekly slot when N is
        // frequent (>=3/month) or left to the automatic pre-exam mock phase
        // (already built into the scheduler) otherwise. This is disclosed to
        // the user rather than silently guessed.
        approach: parsed.mockTestsPerMonth >= 3 ? 'weekly_recurring' : 'pre_exam_phase_only',
        dayOfWeek: 6, // Saturday, editable by the user before confirming
        startTime: '10:00',
        durationMinutes: 90,
      }
    : null;

  const revisionPlan = parsed.wantsWeeklyRevision
    ? {
        dayOfWeek: parsed.revisionDay !== null ? parsed.revisionDay : 0,
        startTime: '18:00',
        durationMinutes: 30,
      }
    : null;

  return {
    userFields: {
      examName: parsed.examName || user.examName,
      examDate,
      hoursPerDay,
      weeklyOffDay: weeklyOffDay ?? null,
      bufferDays: bufferDays ?? user.bufferDays,
    },
    subjects: subjectDrafts,
    mockPlan,
    revisionPlan,
    practiceAfterChapter: parsed.practiceAfterChapter,
    routine: { wakeTime: parsed.wakeTime, sleepTime: parsed.sleepTime },
    warnings,
  };
}

// @desc   Parse a typed/voice study-plan prompt into a full preview (NO database writes).
// @route  POST /api/ai-planner/generate
// @access Private
const generatePlanPreview = async (req, res, next) => {
  try {
    const { text } = req.body;
    if (!text || !text.trim()) {
      return res.status(400).json({ message: 'Please describe your study plan first (type or use the microphone).' });
    }

    const parsed = parseStudyPlanText(text);
    const preview = buildPreview(req.user, parsed);

    // Flag which drafted subjects already exist (so the preview can show
    // "will update" vs "will create").
    const existing = await Subject.find({ user: req.user._id }).select('name');
    const existingNames = new Set(existing.map((s) => s.name));
    preview.subjects = preview.subjects.map((s) => ({ ...s, isNewSubject: !existingNames.has(s.name) }));

    res.json({ preview, parsed: { rawText: parsed.rawText } });
  } catch (err) {
    next(err);
  }
};

// @desc   Confirms a (possibly user-edited) AI Planner preview: creates/updates Subjects,
//         updates User planning preferences, optionally sets up weekly revision/mock
//         exams, then regenerates the full schedule (Tasks) via the same engine every
//         other planner feature uses — so Dashboard, Timeline, Calendar, Schedule,
//         Tasks, Analytics, and Mock/Revision pages all stay in sync automatically.
// @route  POST /api/ai-planner/confirm
// @access Private
const confirmPlan = async (req, res, next) => {
  try {
    const { userFields = {}, subjects = [], mockPlan, revisionPlan } = req.body || {};

    if (!Array.isArray(subjects) || subjects.length === 0) {
      return res.status(400).json({ message: 'At least one subject is required to save a plan.' });
    }

    // 1) Update global planner preferences (only fields actually provided).
    if (userFields.examName !== undefined) req.user.examName = userFields.examName;
    if (userFields.examDate !== undefined && userFields.examDate) req.user.examDate = userFields.examDate;
    if (userFields.hoursPerDay !== undefined && userFields.hoursPerDay) req.user.hoursPerDay = userFields.hoursPerDay;
    if (userFields.weeklyOffDay !== undefined) req.user.weeklyOffDay = userFields.weeklyOffDay;
    if (userFields.bufferDays !== undefined && userFields.bufferDays !== null) req.user.bufferDays = userFields.bufferDays;
    await req.user.save();

    if (!req.user.examDate) {
      return res.status(400).json({ message: 'An exam date is required (edit it in the preview) before saving the plan.' });
    }

    // 2) Create or update each subject. Reuses the exact same fields/shape
    //    subjectController's createSubject/updateSubject use, so the Subject
    //    unique-name-per-user index and all existing validation still apply.
    const createdSubjects = [];
    const updatedSubjects = [];
    for (const draft of subjects) {
      if (!draft.name || !draft.name.trim()) continue;
      // eslint-disable-next-line no-await-in-loop
      let subject = await Subject.findOne({ user: req.user._id, name: draft.name.trim() });
      const chapterData = Array.isArray(draft.subtopics) && draft.subtopics.length
        ? draft.subtopics.map((c) => ({
            name: c.name,
            status: c.status || 'not_started',
            estimatedHours: c.estimatedHours,
            importance: c.importance,
            difficulty: c.difficulty,
            pyqWeightage: c.pyqWeightage,
            notes: c.notes,
          }))
        : undefined;

      if (subject) {
        if (draft.priority !== undefined) subject.priority = draft.priority;
        if (draft.difficulty !== undefined) subject.difficulty = draft.difficulty;
        if (draft.estimatedHours !== undefined) subject.estimatedHours = draft.estimatedHours;
        if (draft.completionDeadline) subject.completionDeadline = draft.completionDeadline;
        // Never silently overwrite chapter progress the user already has —
        // only replace chapters if the subject currently has none.
        if (chapterData && (!subject.subtopics || subject.subtopics.length === 0)) {
          subject.subtopics = chapterData;
        }
        // eslint-disable-next-line no-await-in-loop
        await subject.save();
        updatedSubjects.push(subject);
      } else {
        // eslint-disable-next-line no-await-in-loop
        subject = await Subject.create({
          user: req.user._id,
          name: draft.name.trim(),
          priority: draft.priority || 3,
          difficulty: draft.difficulty || 3,
          estimatedHours: draft.estimatedHours || DEFAULT_SUBJECT_ESTIMATED_HOURS,
          completionDeadline: draft.completionDeadline || undefined,
          color: draft.color,
          subtopics: chapterData || [],
        });
        createdSubjects.push(subject);
      }
    }

    // 3) Auto-fill any missing deadlines (mirrors the "Auto Deadline
    //    Generator" already used elsewhere so nothing is left unplanned).
    const allSubjects = await Subject.find({ user: req.user._id }).sort({ createdAt: 1 });
    const missingDeadline = allSubjects.filter((s) => !s.locked && !s.completionDeadline);
    if (missingDeadline.length) {
      const generated = autoGenerateDeadlines(req.user, allSubjects);
      await Promise.all(
        missingDeadline.map((s) => {
          if (generated[String(s._id)]) s.completionDeadline = generated[String(s._id)];
          return s.save();
        })
      );
    }

    // 4) Optional: weekly revision plan(s), one per newly-touched subject,
    //    staggered so they don't literally overlap.
    const createdRevisionPlans = [];
    if (revisionPlan && revisionPlan.dayOfWeek !== undefined && revisionPlan.dayOfWeek !== null) {
      const targets = [...createdSubjects, ...updatedSubjects];
      let startMinutes = (parseInt(revisionPlan.startTime?.split(':')[0], 10) || 18) * 60 +
        (parseInt(revisionPlan.startTime?.split(':')[1], 10) || 0);
      for (const subject of targets) {
        const existingPlan = await RevisionPlan.findOne({ user: req.user._id, subject: subject.name }); // eslint-disable-line no-await-in-loop
        if (existingPlan) continue;
        const hh = String(Math.floor(startMinutes / 60) % 24).padStart(2, '0');
        const mm = String(startMinutes % 60).padStart(2, '0');
        // eslint-disable-next-line no-await-in-loop
        const plan = await RevisionPlan.create({
          user: req.user._id,
          subject: subject.name,
          daysOfWeek: [revisionPlan.dayOfWeek],
          startTime: `${hh}:${mm}`,
          durationMinutes: revisionPlan.durationMinutes || 30,
        });
        // eslint-disable-next-line no-await-in-loop
        await generateRevisionSessions(req.user._id, plan, req.user.examDate);
        createdRevisionPlans.push(plan);
        startMinutes += revisionPlan.durationMinutes || 30;
      }
    }

    // 5) Optional: recurring mock exam slot ("Full Syllabus" — covers
    //    everything rather than guessing a single subject).
    let createdMockExam = null;
    if (mockPlan && mockPlan.approach === 'weekly_recurring') {
      const already = await MockExam.findOne({ user: req.user._id, subject: 'Full Syllabus', repeatWeekly: true });
      if (!already) {
        createdMockExam = await MockExam.create({
          user: req.user._id,
          subject: 'Full Syllabus',
          title: 'AI Planner Mock Test',
          dayOfWeek: mockPlan.dayOfWeek,
          startTime: mockPlan.startTime || '10:00',
          durationMinutes: mockPlan.durationMinutes || 90,
          repeatWeekly: true,
        });
        const { generateMockExamSessions } = require('../utils/sessionGenerator');
        await generateMockExamSessions(req.user._id, createdMockExam, req.user.examDate);
      }
    }

    // 6) Regenerate the full future schedule from every subject — this is
    //    the same "Dynamic Synchronization Engine" call used everywhere
    //    else, so Dashboard/Timeline/Calendar/Schedule/Tasks/Analytics all
    //    pick up the new plan immediately with no separate/duplicate logic.
    const rebalance = await regenerateFutureSchedule(req.user);

    const finalSubjects = await Subject.find({ user: req.user._id }).sort({ createdAt: 1 });
    const metrics = computePlannerMetrics(req.user, finalSubjects);
    const taskCount = await Task.countDocuments({ user: req.user._id });

    res.status(201).json({
      message: 'Your AI-generated plan has been saved and every module has been synced.',
      user: req.user.toSafeObject(),
      subjectsCreated: createdSubjects.length,
      subjectsUpdated: updatedSubjects.length,
      revisionPlansCreated: createdRevisionPlans.length,
      mockExamCreated: Boolean(createdMockExam),
      subjects: finalSubjects.map((s) => s.toSafeObject(req.user.examDate, metrics[String(s._id)] || null)),
      totalTaskCount: taskCount,
      rebalance: {
        tasksRemoved: rebalance.removed,
        tasksCreated: rebalance.created,
        deadlineWarnings: rebalance.deadlineWarnings,
      },
    });
  } catch (err) {
    next(err);
  }
};

// --- AI Chat Assistant (post-generation) -----------------------------------
// A small set of rule-based intents covering the examples in the spec
// ("I'm tired today", "reduce today's workload", "move revision to
// tomorrow", "I finished early", "reschedule mock test"). Each intent
// updates the SAME Task/Subject collections everything else uses, then
// (where relevant) re-runs the synchronization engine so every module stays
// consistent — no parallel/duplicate state.

function startOfDay(d) {
  const date = new Date(d);
  date.setHours(0, 0, 0, 0);
  return date;
}

// @desc   Natural-language "study mentor" commands that adjust today's/future schedule.
// @route  POST /api/ai-planner/chat
// @access Private
const chatCommand = async (req, res, next) => {
  try {
    const { message } = req.body || {};
    if (!message || !message.trim()) {
      return res.status(400).json({ message: 'Say what you\'d like to change, e.g. "reduce today\'s workload".' });
    }
    const lower = message.toLowerCase();
    const today = startOfDay(new Date());
    const tomorrow = new Date(today.getTime() + 24 * 60 * 60 * 1000);

    const todaysTasks = await Task.find({ user: req.user._id, date: { $gte: today, $lt: tomorrow }, completed: false });

    // Intent: tired / reduce today's workload -> trim each remaining task by ~40%.
    if (/tired|reduce today|lighter|less workload|too much today/.test(lower)) {
      let changed = 0;
      for (const t of todaysTasks) {
        const newDuration = Math.max(10, Math.round((t.durationMinutes * 0.6) / 5) * 5);
        if (newDuration !== t.durationMinutes) {
          t.durationMinutes = newDuration; // eslint-disable-line no-param-reassign
          await t.save(); // eslint-disable-line no-await-in-loop
          changed += 1;
        }
      }
      return res.json({ reply: `Got it — I've lightened today's workload on ${changed} session(s) by ~40%. Rest well!`, tasksChanged: changed });
    }

    // Intent: move revision to tomorrow.
    if (/move revision to tomorrow|reschedule revision/.test(lower)) {
      const revisionToday = todaysTasks.filter((t) => t.type === 'revision');
      for (const t of revisionToday) {
        t.date = tomorrow; // eslint-disable-line no-param-reassign
        await t.save(); // eslint-disable-line no-await-in-loop
      }
      return res.json({ reply: `Moved ${revisionToday.length} revision session(s) to tomorrow.`, tasksChanged: revisionToday.length });
    }

    // Intent: finished early -> mark today's remaining sessions complete.
    if (/finished early|done for today|completed everything/.test(lower)) {
      for (const t of todaysTasks) {
        t.completed = true; // eslint-disable-line no-param-reassign
        t.completedAt = new Date(); // eslint-disable-line no-param-reassign
        await t.save(); // eslint-disable-line no-await-in-loop
      }
      return res.json({ reply: `Nice work! Marked ${todaysTasks.length} remaining session(s) for today as complete.`, tasksChanged: todaysTasks.length });
    }

    // Intent: reschedule mock test -> push any mock_exam session today to tomorrow.
    if (/reschedule mock|move mock/.test(lower)) {
      const mocksToday = todaysTasks.filter((t) => t.type === 'mock_exam');
      for (const t of mocksToday) {
        t.date = tomorrow; // eslint-disable-line no-param-reassign
        await t.save(); // eslint-disable-line no-await-in-loop
      }
      return res.json({ reply: `Rescheduled ${mocksToday.length} mock test session(s) to tomorrow.`, tasksChanged: mocksToday.length });
    }

    // Intent: increase difficulty -> bump priority/difficulty of subjects with sessions today, then rebalance.
    if (/increase difficulty|make it harder|more challenging/.test(lower)) {
      const subjectNames = [...new Set(todaysTasks.map((t) => t.subject))];
      const subjectsToUpdate = await Subject.find({ user: req.user._id, name: { $in: subjectNames } });
      for (const s of subjectsToUpdate) {
        s.difficulty = Math.min(5, (s.difficulty || 3) + 1); // eslint-disable-line no-param-reassign
        await s.save(); // eslint-disable-line no-await-in-loop
      }
      const rebalance = await regenerateFutureSchedule(req.user);
      return res.json({
        reply: `Increased difficulty for ${subjectsToUpdate.length} subject(s) — regenerated the upcoming schedule accordingly.`,
        tasksChanged: rebalance.created,
      });
    }

    return res.json({
      reply:
        "I can help with things like: \"I'm tired today\", \"reduce today's workload\", \"move revision to tomorrow\", \"I finished early\", \"reschedule mock test\", or \"increase difficulty\". Try one of those, or edit your plan directly on the Subjects/Schedule pages.",
      tasksChanged: 0,
    });
  } catch (err) {
    next(err);
  }
};

module.exports = { generatePlanPreview, confirmPlan, chatCommand };
