const StudyPlan = require('../models/StudyPlan');
const Task = require('../models/Task');
const Subject = require('../models/Subject');
const { generateScheduleAI } = require('../utils/aiService');
const { computePlannerMetrics, autoGenerateDeadlines, generateDeadlineAwareSchedule, startOfDay } = require('../utils/deadlinePlanner');

const TASK_TITLES = {
  study: (subject) => `Study ${subject}`,
  revision: (subject) => `Revise ${subject}`,
  mock_exam: (subject) => `${subject} Mock Test`,
  practice: (subject) => `Practice ${subject} PYQs`,
};

// @desc   Generate a new AI study schedule from exam date, subjects & hours/day.
//         Persists the plan and creates Task documents for each scheduled day
//         (only future/current tasks that don't already exist are created).
//
//         Planning Mode (see Planner Settings):
//           - 'subject_deadline' (default): every subject is scheduled only up
//             to its own Completion Deadline; once that passes, only
//             revisions/mocks/practice are scheduled for it — never new
//             learning — until the exam's revision + mock-test phases.
//           - 'exam_deadline': legacy behavior — every subject is scheduled
//             continuously all the way to the exam date.
// @route  POST /api/plan/generate
// @access Private
const generatePlan = async (req, res, next) => {
  try {
    const { examDate, hoursPerDay, subjects: bodySubjects, planningMode: bodyPlanningMode } = req.body;

    if (!examDate || !hoursPerDay) {
      return res.status(400).json({ message: 'examDate and hoursPerDay are required' });
    }
    if (new Date(examDate) < new Date(new Date().setHours(0, 0, 0, 0))) {
      return res.status(400).json({ message: 'examDate must be today or in the future' });
    }

    // Save preferences on the user profile too, for convenience
    req.user.examDate = examDate;
    req.user.hoursPerDay = hoursPerDay;
    if (bodyPlanningMode === 'subject_deadline' || bodyPlanningMode === 'exam_deadline') {
      req.user.planningMode = bodyPlanningMode;
    }
    if (Array.isArray(bodySubjects) && bodySubjects.length) {
      req.user.subjects = bodySubjects.map((s) => ({
        name: s.name,
        priority: Number(s.priority) || 3,
        difficulty: Number(s.difficulty) || 3,
      }));
    }
    await req.user.save();

    const planningMode = req.user.planningMode || 'subject_deadline';
    const subjectDocs = await Subject.find({ user: req.user._id }).sort({ createdAt: 1 });

    let days;
    let generatedBy;
    const deadlineWarnings = [];

    if (planningMode === 'subject_deadline' && subjectDocs.length > 0) {
      // Auto-generate a deadline for any subject that doesn't have one yet.
      const missingDeadline = subjectDocs.filter((s) => !s.completionDeadline);
      if (missingDeadline.length) {
        const generated = autoGenerateDeadlines(req.user, subjectDocs);
        await Promise.all(
          missingDeadline.map((s) => {
            s.completionDeadline = generated[String(s._id)];
            return s.save();
          })
        );
      }

      const schedule = generateDeadlineAwareSchedule({ user: req.user, subjects: subjectDocs });
      days = schedule.days;
      generatedBy = 'deadline-aware';

      // Recompute + persist per-subject metrics (expected completion date,
      // required daily hours, risk score) so Subjects/Dashboard/Timeline/
      // Analytics all reflect the freshly generated plan immediately.
      const metrics = computePlannerMetrics(req.user, subjectDocs);
      await Promise.all(
        subjectDocs.map((s) => {
          const m = metrics[String(s._id)];
          if (!m) return Promise.resolve();
          s.expectedCompletionDate = m.expectedCompletionDate;
          s.requiredDailyHours = m.requiredDailyHours;
          s.deadlineRiskScore = m.deadlineRiskScore;
          if (m.warning) deadlineWarnings.push({ subject: s.name, warning: m.warning, suggestions: m.suggestions });
          return s.save();
        })
      );
    } else {
      // Legacy behaviour: schedule every subject continuously until the exam
      // date. Uses the body-provided lightweight subjects if given, otherwise
      // a simplified view of the user's saved Subject documents.
      const legacySubjects =
        Array.isArray(bodySubjects) && bodySubjects.length
          ? bodySubjects.map((s) => ({ name: s.name, priority: Number(s.priority) || 3, difficulty: Number(s.difficulty) || 3 }))
          : subjectDocs.map((s) => ({ name: s.name, priority: s.priority, difficulty: s.difficulty }));

      if (!legacySubjects.length) {
        return res.status(400).json({ message: 'Add at least one subject before generating a plan' });
      }

      const ai = await generateScheduleAI({ examDate, hoursPerDay, subjects: legacySubjects });
      days = ai.days;
      generatedBy = ai.generatedBy;
    }

    const planSubjectsSummary = subjectDocs.length
      ? subjectDocs.map((s) => ({ name: s.name, priority: s.priority, difficulty: s.difficulty }))
      : (Array.isArray(bodySubjects) ? bodySubjects : []).map((s) => ({
          name: s.name,
          priority: Number(s.priority) || 3,
          difficulty: Number(s.difficulty) || 3,
        }));

    const plan = await StudyPlan.create({
      user: req.user._id,
      examDate,
      hoursPerDay,
      subjects: planSubjectsSummary,
      days,
      generatedBy,
    });

    // Turn each day's breakdown into individual Task documents.
    // Skip days that already have AI-generated tasks to avoid duplicates.
    const createdTasks = [];
    for (const day of days) {
      const dayStart = new Date(day.date);
      dayStart.setHours(0, 0, 0, 0);
      const dayEnd = new Date(day.date);
      dayEnd.setHours(23, 59, 59, 999);

      // eslint-disable-next-line no-await-in-loop
      const existingCount = await Task.countDocuments({
        user: req.user._id,
        date: { $gte: dayStart, $lte: dayEnd },
        source: 'ai',
      });
      if (existingCount > 0) continue;

      for (const b of day.breakdown) {
        if (!b.minutes || b.minutes <= 0) continue;
        const taskType = ['study', 'revision', 'mock_exam', 'practice'].includes(b.taskType) ? b.taskType : 'study';
        const subjMeta = planSubjectsSummary.find((s) => s.name === b.subject) || {};
        const subjectDoc = subjectDocs.find((s) => s.name === b.subject);
        // eslint-disable-next-line no-await-in-loop
        const task = await Task.create({
          user: req.user._id,
          subject: b.subject,
          title: TASK_TITLES[taskType](b.subject),
          date: day.date,
          durationMinutes: b.minutes,
          priority: subjMeta.priority || 3,
          source: 'ai',
          type: taskType,
          subjectId: subjectDoc ? subjectDoc._id : null,
        });
        createdTasks.push(task);
      }
    }

    res.status(201).json({ plan, tasksCreated: createdTasks.length, generatedBy, planningMode, deadlineWarnings });
  } catch (err) {
    next(err);
  }
};

// @desc   Get the most recent study plan for the current user
// @route  GET /api/plan/latest
// @access Private
const getLatestPlan = async (req, res, next) => {
  try {
    const plan = await StudyPlan.findOne({ user: req.user._id }).sort({ createdAt: -1 });
    res.json({ plan });
  } catch (err) {
    next(err);
  }
};

// @desc   Timeline/Gantt-chart data: each subject's window (today -> its
//         deadline), plus the shared revision phase and mock-test phase
//         leading up to the exam.
// @route  GET /api/plan/timeline
// @access Private
const getTimeline = async (req, res, next) => {
  try {
    const user = req.user;
    const subjects = await Subject.find({ user: user._id }).sort({ createdAt: 1 });
    const metrics = computePlannerMetrics(user, subjects);
    const today = startOfDay(new Date());
    const examDate = user.examDate ? startOfDay(user.examDate) : null;
    const bufferDays = user.bufferDays || 0;
    const revisionStart = examDate ? new Date(examDate.getTime() - bufferDays * 24 * 60 * 60 * 1000) : null;
    const mockStart = examDate
      ? new Date(examDate.getTime() - Math.min(bufferDays, 4) * 24 * 60 * 60 * 1000)
      : null;

    const bars = subjects.map((s) => {
      const m = metrics[String(s._id)] || {};
      const barStart = s.planningStartDate ? startOfDay(s.planningStartDate) : today;
      return {
        id: s._id,
        name: s.name,
        color: s.color,
        start: barStart,
        end: m.deadline || examDate || today,
        planningStartDate: s.planningStartDate || null,
        completionDeadline: s.completionDeadline || null,
        dormant: Boolean(m.dormant),
        completionPercent: s.completionPercent(),
        status: m.status || 'on_track',
        locked: s.locked,
        paused: s.paused,
      };
    });

    res.json({
      today,
      examDate,
      revisionStart,
      mockStart,
      bars,
      examName: user.examName,
    });
  } catch (err) {
    next(err);
  }
};

module.exports = { generatePlan, getLatestPlan, getTimeline };
