const Subject = require('../models/Subject');
const RevisionPlan = require('../models/RevisionPlan');
const Task = require('../models/Task');
const { checkDeadlineFeasible } = require('../utils/scheduleValidation');
const { generateChapterRevisions } = require('../utils/chapterRevision');
const { GATE_CSE_SUBJECTS } = require('../utils/gateCsePreset');
const { computePlannerMetrics, autoGenerateDeadlines } = require('../utils/deadlinePlanner');
const { regenerateFutureSchedule } = require('../utils/scheduleRebalancer');

const CHAPTER_FIELDS = ['name', 'status', 'estimatedHours', 'importance', 'difficulty', 'pyqWeightage', 'notes'];
const SUBJECT_FIELDS = [
  'name',
  'priority',
  'difficulty',
  'weightage',
  'estimatedHours',
  'color',
  'notes',
  'targetCompletionDate',
  // --- Subject Planning Window fields ---
  'planningStartDate',
  'completionDeadline',
  'planningMode',
  'allowDeadlineExtension',
  'locked',
  'paused',
];

// Fields that, if changed, require the future schedule to be regenerated so
// the Daily Planner/Calendar/Timeline/Dashboard/Analytics/AI Suggestions never
// go stale (the Dynamic Synchronization Engine).
const RESCHEDULE_TRIGGER_FIELDS = [
  'planningStartDate',
  'completionDeadline',
  'estimatedHours',
  'priority',
  'difficulty',
  'weightage',
  'planningMode',
  'allowDeadlineExtension',
  'locked',
  'paused',
];

const validatePlanningWindow = (start, deadline) => {
  if (start && deadline && new Date(start) > new Date(deadline)) {
    return 'Planning Start Date must be on or before the Completion Deadline';
  }
  return null;
};

// Attaches live deadline metrics (remaining hours/days, required vs available
// hours/day, warnings, status, AI suggestion) to a single subject's safe
// object. Needs every one of the user's subjects (not just this one) because
// the daily hours pool is shared/weighted across all currently-active subjects.
const withMetrics = async (user, subject) => {
  const allSubjects = await Subject.find({ user: user._id }).sort({ createdAt: 1 });
  const metrics = computePlannerMetrics(user, allSubjects);
  return subject.toSafeObject(user.examDate, metrics[String(subject._id)] || null);
};

const cleanChapterInput = (s) => {
  const out = { name: s.name || s };
  CHAPTER_FIELDS.forEach((f) => {
    if (s[f] !== undefined) out[f] = s[f];
  });
  return out;
};

// @desc   List all subjects for the current user, each with completion % and deadline warning
// @route  GET /api/subjects
// @access Private
const getSubjects = async (req, res, next) => {
  try {
    const subjects = await Subject.find({ user: req.user._id }).sort({ createdAt: 1 });
    const examDate = req.user.examDate;
    const metrics = computePlannerMetrics(req.user, subjects);
    res.json({ subjects: subjects.map((s) => s.toSafeObject(examDate, metrics[String(s._id)] || null)) });
  } catch (err) {
    next(err);
  }
};

// @desc   Create a subject (optionally with initial subtopics/chapters)
// @route  POST /api/subjects
// @access Private
const createSubject = async (req, res, next) => {
  try {
    const { name, subtopics, planningStartDate, completionDeadline } = req.body;
    if (!name) return res.status(400).json({ message: 'Subject name is required' });

    const windowError = validatePlanningWindow(planningStartDate, completionDeadline);
    if (windowError) return res.status(400).json({ message: windowError });

    const existing = await Subject.findOne({ user: req.user._id, name: name.trim() });
    if (existing) return res.status(409).json({ message: 'A subject with this name already exists' });

    const data = { user: req.user._id, name: name.trim() };
    SUBJECT_FIELDS.slice(1).forEach((f) => {
      if (req.body[f] !== undefined) data[f] = req.body[f];
    });
    data.subtopics = Array.isArray(subtopics) ? subtopics.map(cleanChapterInput) : [];

    const subject = await Subject.create(data);

    // Auto Deadline Generator: if the user left the deadline blank, spread one
    // in intelligently based on priority/difficulty/weightage/estimated hours/
    // exam date/buffer days, alongside the user's other subjects.
    if (!subject.completionDeadline) {
      const allSubjects = await Subject.find({ user: req.user._id }).sort({ createdAt: 1 });
      const generated = autoGenerateDeadlines(req.user, allSubjects);
      if (generated[String(subject._id)]) {
        subject.completionDeadline = generated[String(subject._id)];
        await subject.save();
      }
    }

    // Adding a subject mid-plan must recalculate remaining days/hours and
    // rebalance every OTHER future (non-locked, non-completed) session too —
    // this is what lets a subject be added in the middle of preparation
    // without disturbing history.
    const rebalance = await regenerateFutureSchedule(req.user);

    const warning = checkDeadlineFeasible(subject.targetCompletionDate, req.user.examDate);
    const safeSubject = await withMetrics(req.user, subject);
    res.status(201).json({
      subject: safeSubject,
      warning,
      rebalance: { tasksRemoved: rebalance.removed, tasksCreated: rebalance.created, deadlineWarnings: rebalance.deadlineWarnings },
    });
  } catch (err) {
    next(err);
  }
};

// @desc   Seed the 13 standard GATE CSE subjects (with chapters) for the current user.
//         Skips any subject the user already has (matched by name).
// @route  POST /api/subjects/seed-gate-cse
// @access Private
const seedGateCse = async (req, res, next) => {
  try {
    const existingNames = new Set((await Subject.find({ user: req.user._id }).select('name')).map((s) => s.name));

    const toCreate = GATE_CSE_SUBJECTS.filter((s) => !existingNames.has(s.name)).map((s) => ({
      ...s,
      user: req.user._id,
      subtopics: s.subtopics.map((c) => ({ ...c, status: 'not_started' })),
    }));

    const created = toCreate.length ? await Subject.insertMany(toCreate) : [];
    res.status(201).json({
      created: created.length,
      skipped: GATE_CSE_SUBJECTS.length - created.length,
      subjects: created.map((s) => s.toSafeObject(req.user.examDate)),
    });
  } catch (err) {
    next(err);
  }
};

// @desc   Update a subject's details
// @route  PUT /api/subjects/:id
// @access Private
const updateSubject = async (req, res, next) => {
  try {
    const subject = await Subject.findOne({ _id: req.params.id, user: req.user._id });
    if (!subject) return res.status(404).json({ message: 'Subject not found' });

    const nextStart = req.body.planningStartDate !== undefined ? req.body.planningStartDate : subject.planningStartDate;
    const nextDeadline = req.body.completionDeadline !== undefined ? req.body.completionDeadline : subject.completionDeadline;
    const windowError = validatePlanningWindow(nextStart, nextDeadline);
    if (windowError) return res.status(400).json({ message: windowError });

    // Editable Total (Estimated) Study Hours: Estimated Hours must stay > 0,
    // and must never be dropped below the hours already logged as completed
    // (existing completed chapter records are never deleted or altered here).
    if (req.body.estimatedHours !== undefined) {
      const nextEstimated = Number(req.body.estimatedHours);
      if (!(nextEstimated > 0)) {
        return res.status(400).json({ message: 'Estimated Hours must be greater than zero' });
      }
      const { completedHours } = subject.hoursSummary();
      if (completedHours > nextEstimated) {
        return res.status(400).json({
          message: `Estimated Hours (${nextEstimated}h) cannot be less than the ${completedHours}h already completed`,
        });
      }
    }

    const scheduleAffectingChange = RESCHEDULE_TRIGGER_FIELDS.some(
      (f) => req.body[f] !== undefined && String(req.body[f]) !== String(subject[f])
    );

    SUBJECT_FIELDS.forEach((f) => {
      if (req.body[f] !== undefined) subject[f] = req.body[f];
    });

    await subject.save();

    // If the deadline was cleared out, auto-generate a fresh one rather than
    // leaving the subject with no plan at all.
    if (!subject.completionDeadline) {
      const allSubjects = await Subject.find({ user: req.user._id }).sort({ createdAt: 1 });
      const generated = autoGenerateDeadlines(req.user, allSubjects);
      if (generated[String(subject._id)]) {
        subject.completionDeadline = generated[String(subject._id)];
        await subject.save();
      }
    }

    // Editing planning window / hours / difficulty / priority / weightage /
    // mode / extension / lock / pause must regenerate only the FUTURE
    // schedule, preserving completed tasks, history, and locked subjects.
    let rebalance = { removed: 0, created: 0, deadlineWarnings: [] };
    if (scheduleAffectingChange && !subject.locked) {
      rebalance = await regenerateFutureSchedule(req.user);
    }

    const warning = checkDeadlineFeasible(subject.targetCompletionDate, req.user.examDate);
    const safeSubject = await withMetrics(req.user, subject);
    res.json({
      subject: safeSubject,
      warning,
      rebalance: { tasksRemoved: rebalance.removed, tasksCreated: rebalance.created, deadlineWarnings: rebalance.deadlineWarnings },
    });
  } catch (err) {
    next(err);
  }
};

// @desc   Manually pin a subject's Remaining Hours to a specific value,
//         independent of (estimatedHours - completedHours). Used when the
//         user already knows part of the subject and wants the planner to
//         plan for fewer (or, in principle, more, up to Estimated Hours)
//         hours than the derived figure. Completed Hours is never touched.
//         The planner keeps using this value on every future recalculation
//         until "Reset Remaining Hours" is called.
// @route  PATCH /api/subjects/:id/remaining-hours
// @access Private
const setRemainingHours = async (req, res, next) => {
  try {
    const subject = await Subject.findOne({ _id: req.params.id, user: req.user._id });
    if (!subject) return res.status(404).json({ message: 'Subject not found' });

    const { remainingHours } = req.body;
    if (remainingHours === undefined || remainingHours === null || Number.isNaN(Number(remainingHours))) {
      return res.status(400).json({ message: 'remainingHours is required' });
    }
    const value = Number(remainingHours);
    if (value < 0) {
      return res.status(400).json({ message: 'Remaining Hours cannot be negative' });
    }
    if (subject.estimatedHours && value > subject.estimatedHours) {
      return res.status(400).json({
        message: `Remaining Hours (${value}h) cannot exceed Estimated Hours (${subject.estimatedHours}h)`,
      });
    }

    subject.remainingHoursOverride = value;
    subject.remainingHoursAutoCalculated = false;
    subject.remainingHoursOverrideAt = new Date();
    await subject.save();

    // Remaining Hours drives every downstream number the planner produces —
    // regenerate the future schedule so today's/weekly/monthly timetable,
    // revision planning, AI recommendations, completion forecast, and
    // dashboard/productivity analytics all pick up the new figure instantly.
    const rebalance = subject.locked ? { removed: 0, created: 0, deadlineWarnings: [] } : await regenerateFutureSchedule(req.user);

    const safeSubject = await withMetrics(req.user, subject);
    res.json({
      subject: safeSubject,
      rebalance: { tasksRemoved: rebalance.removed, tasksCreated: rebalance.created, deadlineWarnings: rebalance.deadlineWarnings },
    });
  } catch (err) {
    next(err);
  }
};

// @desc   Reset Remaining Hours back to auto-calculated
//         (estimatedHours - completedHours), clearing any manual override.
// @route  PATCH /api/subjects/:id/remaining-hours/reset
// @access Private
const resetRemainingHours = async (req, res, next) => {
  try {
    const subject = await Subject.findOne({ _id: req.params.id, user: req.user._id });
    if (!subject) return res.status(404).json({ message: 'Subject not found' });

    subject.remainingHoursAutoCalculated = true;
    subject.remainingHoursOverride = null;
    subject.remainingHoursOverrideAt = undefined;
    await subject.save();

    const rebalance = subject.locked ? { removed: 0, created: 0, deadlineWarnings: [] } : await regenerateFutureSchedule(req.user);

    const safeSubject = await withMetrics(req.user, subject);
    res.json({
      subject: safeSubject,
      rebalance: { tasksRemoved: rebalance.removed, tasksCreated: rebalance.created, deadlineWarnings: rebalance.deadlineWarnings },
    });
  } catch (err) {
    next(err);
  }
};

// @desc   Manual override actions for a subject's deadline/schedule:
//         extend / shorten (by N days, or to a specific date), pause, resume,
//         lock, unlock. Locked subjects are still editable here — locking
//         only stops *automatic* rescheduling from touching them.
// @route  PATCH /api/subjects/:id/override
// @access Private
const overrideSubject = async (req, res, next) => {
  try {
    const subject = await Subject.findOne({ _id: req.params.id, user: req.user._id });
    if (!subject) return res.status(404).json({ message: 'Subject not found' });

    const { action, days, date } = req.body;
    const DAY_MS = 24 * 60 * 60 * 1000;
    const currentDeadline = subject.completionDeadline ? new Date(subject.completionDeadline) : new Date();

    switch (action) {
      case 'extend': {
        subject.completionDeadline = date
          ? new Date(date)
          : new Date(currentDeadline.getTime() + (Number(days) || 1) * DAY_MS);
        break;
      }
      case 'shorten': {
        subject.completionDeadline = date
          ? new Date(date)
          : new Date(currentDeadline.getTime() - (Number(days) || 1) * DAY_MS);
        break;
      }
      case 'pause':
        subject.paused = true;
        break;
      case 'resume':
        subject.paused = false;
        break;
      case 'lock':
        subject.locked = true;
        break;
      case 'unlock':
        subject.locked = false;
        break;
      default:
        return res.status(400).json({ message: 'Unknown override action. Use extend, shorten, pause, resume, lock, or unlock.' });
    }

    await subject.save();

    // Every override (extend/shorten/pause/resume/lock/unlock) is a schedule-
    // affecting change — regenerate the future plan (locked subjects are
    // automatically skipped by regenerateFutureSchedule itself).
    const rebalance = await regenerateFutureSchedule(req.user);

    const safeSubject = await withMetrics(req.user, subject);
    res.json({
      subject: safeSubject,
      rebalance: { tasksRemoved: rebalance.removed, tasksCreated: rebalance.created, deadlineWarnings: rebalance.deadlineWarnings },
    });
  } catch (err) {
    next(err);
  }
};

// @desc   (Re)runs the Auto Deadline Generator for every subject that doesn't
//         yet have a completion deadline (or, with force=true, for every
//         non-locked subject), spreading deadlines intelligently across the
//         runway before the exam.
// @route  POST /api/subjects/auto-deadlines
// @access Private
const generateAutoDeadlines = async (req, res, next) => {
  try {
    const force = Boolean(req.body?.force);
    const allSubjects = await Subject.find({ user: req.user._id }).sort({ createdAt: 1 });
    const targets = allSubjects.filter((s) => !s.locked && (force || !s.completionDeadline));
    const generated = autoGenerateDeadlines(req.user, allSubjects.filter((s) => !s.locked));

    await Promise.all(
      targets.map((s) => {
        if (generated[String(s._id)]) s.completionDeadline = generated[String(s._id)];
        return s.save();
      })
    );

    const rebalance = targets.length ? await regenerateFutureSchedule(req.user) : { removed: 0, created: 0, deadlineWarnings: [] };

    const refreshed = await Subject.find({ user: req.user._id }).sort({ createdAt: 1 });
    const metrics = computePlannerMetrics(req.user, refreshed);
    res.json({
      updated: targets.length,
      subjects: refreshed.map((s) => s.toSafeObject(req.user.examDate, metrics[String(s._id)] || null)),
      rebalance: { tasksRemoved: rebalance.removed, tasksCreated: rebalance.created, deadlineWarnings: rebalance.deadlineWarnings },
    });
  } catch (err) {
    next(err);
  }
};

// @desc   Delete a subject (and its revision plans / auto-generated revisions)
// @route  DELETE /api/subjects/:id
// @access Private
const deleteSubject = async (req, res, next) => {
  try {
    const subject = await Subject.findOneAndDelete({ _id: req.params.id, user: req.user._id });
    if (!subject) return res.status(404).json({ message: 'Subject not found' });

    // Remove this subject's future tasks/reminders. Completed history for it
    // is intentionally left in place (see "Completed history should remain
    // unchanged unless the user chooses to remove it").
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    await RevisionPlan.deleteMany({ user: req.user._id, subject: subject.name });
    await Task.deleteMany({ user: req.user._id, subjectId: subject._id, completed: false, date: { $gte: today } });

    // Rebalance every remaining (non-locked) subject's future schedule now
    // that this subject's share of the daily-hours pool is freed up.
    const rebalance = await regenerateFutureSchedule(req.user);

    res.json({
      message: 'Subject deleted',
      rebalance: { tasksRemoved: rebalance.removed, tasksCreated: rebalance.created, deadlineWarnings: rebalance.deadlineWarnings },
    });
  } catch (err) {
    next(err);
  }
};

// @desc   Add a subtopic/chapter to a subject
// @route  POST /api/subjects/:id/subtopics
// @access Private
const addSubtopic = async (req, res, next) => {
  try {
    const { name } = req.body;
    if (!name) return res.status(400).json({ message: 'Chapter name is required' });

    const subject = await Subject.findOne({ _id: req.params.id, user: req.user._id });
    if (!subject) return res.status(404).json({ message: 'Subject not found' });

    subject.subtopics.push(cleanChapterInput(req.body));
    await subject.save();
    const safeSubject = await withMetrics(req.user, subject);
    res.status(201).json({ subject: safeSubject });
  } catch (err) {
    next(err);
  }
};

// @desc   Update a subtopic/chapter (name, status, estimatedHours, importance,
//         difficulty, pyqWeightage, notes). Marking status as 'completed' for
//         the first time auto-generates its 1/3/7/15/30-day + pre-exam revisions.
// @route  PUT /api/subjects/:id/subtopics/:subtopicId
// @access Private
const updateSubtopic = async (req, res, next) => {
  try {
    const subject = await Subject.findOne({ _id: req.params.id, user: req.user._id });
    if (!subject) return res.status(404).json({ message: 'Subject not found' });

    const subtopic = subject.subtopics.id(req.params.subtopicId);
    if (!subtopic) return res.status(404).json({ message: 'Chapter not found' });

    const wasCompleted = subtopic.status === 'completed';

    CHAPTER_FIELDS.forEach((f) => {
      if (req.body[f] !== undefined) subtopic[f] = req.body[f];
    });

    let revisionsCreated = 0;
    if (subtopic.status === 'completed' && !wasCompleted) {
      subtopic.completionDate = new Date();
    } else if (subtopic.status !== 'completed') {
      subtopic.completionDate = undefined;
    }

    await subject.save();

    if (subtopic.status === 'completed' && !wasCompleted) {
      const created = await generateChapterRevisions({
        userId: req.user._id,
        subject,
        subtopic,
        examDate: req.user.examDate,
        revisionIntervals: req.user.revisionIntervals,
        bufferDaysBeforeExam: req.user.bufferDays,
      });
      revisionsCreated = created.length;
    } else if (subtopic.status !== 'completed' && wasCompleted) {
      // Un-completing a chapter removes its not-yet-done auto-revisions
      await generateChapterRevisions({
        userId: req.user._id,
        subject,
        subtopic: { ...subtopic.toObject(), completionDate: null },
        examDate: req.user.examDate,
        revisionIntervals: req.user.revisionIntervals,
      });
    }

    res.json({ subject: await withMetrics(req.user, subject), revisionsCreated });
  } catch (err) {
    next(err);
  }
};

// @desc   Delete a subtopic/chapter
// @route  DELETE /api/subjects/:id/subtopics/:subtopicId
// @access Private
const deleteSubtopic = async (req, res, next) => {
  try {
    const subject = await Subject.findOne({ _id: req.params.id, user: req.user._id });
    if (!subject) return res.status(404).json({ message: 'Subject not found' });

    const subtopicId = req.params.subtopicId;
    subject.subtopics.pull({ _id: subtopicId });
    await subject.save();
    await Task.deleteMany({ user: req.user._id, chapterId: subtopicId, completed: false });
    res.json({ subject: await withMetrics(req.user, subject) });
  } catch (err) {
    next(err);
  }
};

module.exports = {
  getSubjects,
  createSubject,
  seedGateCse,
  updateSubject,
  setRemainingHours,
  resetRemainingHours,
  overrideSubject,
  generateAutoDeadlines,
  deleteSubject,
  addSubtopic,
  updateSubtopic,
  deleteSubtopic,
};
