const Task = require('../models/Task');

const DAY_MS = 24 * 60 * 60 * 1000;

/**
 * When a chapter is marked completed, auto-creates its full spaced-repetition
 * revision trail as 'revision' type Task documents:
 *   completionDate + each interval in user.revisionIntervals (default 1/3/7/15/30 days)
 *   + one final "Before Exam" revision a few days ahead of the exam date
 *     (skipped if the exam is already too close, or there's no exam date).
 *
 * Idempotent: clears any previously auto-generated, not-yet-completed
 * revisions for this exact chapter before recreating them, so editing the
 * chapter's completion status or the user's revisionIntervals doesn't
 * duplicate sessions.
 */
async function generateChapterRevisions({ userId, subject, subtopic, examDate, revisionIntervals, bufferDaysBeforeExam = 3 }) {
  await Task.deleteMany({
    user: userId,
    subjectId: subject._id,
    chapterId: subtopic._id,
    type: 'revision',
    completed: false,
  });

  if (!subtopic.completionDate) return [];

  const intervals = Array.isArray(revisionIntervals) && revisionIntervals.length
    ? revisionIntervals
    : [1, 3, 7, 15, 30];

  const completionDate = new Date(subtopic.completionDate);
  const exam = examDate ? new Date(examDate) : null;
  const created = [];

  const makeRevision = async (date, stageLabel) => {
    const dayStart = new Date(date);
    dayStart.setHours(0, 0, 0, 0);
    // Don't schedule a revision on or after the exam date itself (except the
    // dedicated "Before Exam" one, handled separately below).
    if (exam && dayStart >= new Date(new Date(exam).setHours(0, 0, 0, 0))) return;

    const task = await Task.create({
      user: userId,
      subject: subject.name,
      title: `Revise ${subject.name} — ${subtopic.name}`,
      subtopic: subtopic.name,
      notes: `Auto-scheduled ${stageLabel} revision`,
      date: dayStart,
      durationMinutes: 30,
      type: 'revision',
      source: 'ai',
      autoGenerated: true,
      subjectId: subject._id,
      chapterId: subtopic._id,
      revisionStage: stageLabel,
    });
    created.push(task);
  };

  for (const days of intervals) {
    // eslint-disable-next-line no-await-in-loop
    await makeRevision(new Date(completionDate.getTime() + days * DAY_MS), `Day ${days}`);
  }

  if (exam) {
    const preExamDate = new Date(exam.getTime() - bufferDaysBeforeExam * DAY_MS);
    if (preExamDate > completionDate) {
      // eslint-disable-next-line no-await-in-loop
      const dayStart = new Date(preExamDate);
      dayStart.setHours(0, 0, 0, 0);
      const task = await Task.create({
        user: userId,
        subject: subject.name,
        title: `Revise ${subject.name} — ${subtopic.name}`,
        subtopic: subtopic.name,
        notes: 'Auto-scheduled final revision before the exam',
        date: dayStart,
        durationMinutes: 30,
        type: 'revision',
        source: 'ai',
        autoGenerated: true,
        subjectId: subject._id,
        chapterId: subtopic._id,
        revisionStage: 'Before Exam',
      });
      created.push(task);
    }
  }

  return created;
}

module.exports = { generateChapterRevisions };
