// Dynamic Synchronization Engine
// -------------------------------
// Whenever anything that affects the schedule changes (a subject's planning
// window/hours/priority/difficulty, pause/resume, lock/unlock, a subject
// being added or removed, or global settings like hoursPerDay/examDate/
// bufferDays/weeklyOffDay/planningMode), this is the single place that
// regenerates the plan going forward — without ever touching:
//   - completed tasks (any day, any subject)
//   - tasks belonging to a LOCKED subject (locked subjects are frozen)
//   - tasks strictly in the past (before today)
//
// It reuses the existing generateDeadlineAwareSchedule() so all the deadline/
// pause/planning-window logic stays in one place (utils/deadlinePlanner.js).

const Task = require('../models/Task');
const Subject = require('../models/Subject');
const { generateDeadlineAwareSchedule, computePlannerMetrics, startOfDay } = require('./deadlinePlanner');

const TASK_TITLES = {
  study: (subject) => `Study ${subject}`,
  revision: (subject) => `Revise ${subject}`,
  mock_exam: (subject) => `${subject} Mock Test`,
  practice: (subject) => `Practice ${subject} PYQs`,
};

/**
 * Regenerates every future, auto-generated, not-yet-completed task for the
 * user's non-locked subjects, then recomputes + persists each subject's
 * live metrics (expectedCompletionDate, requiredDailyHours, deadlineRiskScore,
 * forecastStatus, lastRescheduledAt).
 *
 * Locked subjects are entirely excluded from regeneration — both their
 * existing future tasks AND their contribution to the shared daily-hours pool
 * are left untouched, per "Locked: Planner must never automatically modify it."
 *
 * Returns { removed, created, deadlineWarnings, subjects }.
 */
async function regenerateFutureSchedule(user) {
  if (!user.examDate) {
    // Nothing to schedule against yet (no exam date set) — just recompute
    // whatever metrics we can, don't touch tasks.
    return { removed: 0, created: 0, deadlineWarnings: [], subjects: [] };
  }

  const today = startOfDay(new Date());
  const allSubjects = await Subject.find({ user: user._id }).sort({ createdAt: 1 });
  const schedulableSubjects = allSubjects.filter((s) => !s.locked);
  const lockedSubjectNames = new Set(allSubjects.filter((s) => s.locked).map((s) => s.name));

  // 1) Wipe future, incomplete, auto-generated tasks for non-locked subjects
  //    only. Manual (source: 'manual') tasks the user typed in by hand are
  //    left alone too — only planner-authored ('source: ai' / autoGenerated)
  //    sessions are regenerated.
  const removeResult = await Task.deleteMany({
    user: user._id,
    date: { $gte: today },
    completed: false,
    source: 'ai',
    subject: { $nin: Array.from(lockedSubjectNames) },
  });

  // 2) Regenerate the schedule from today onward for the schedulable subjects.
  const schedule = generateDeadlineAwareSchedule({ user, subjects: schedulableSubjects });

  let created = 0;
  for (const day of schedule.days) {
    if (startOfDay(day.date) < today) continue; // safety: never touch the past
    for (const b of day.breakdown) {
      if (!b.minutes || b.minutes <= 0) continue;
      const taskType = ['study', 'revision', 'mock_exam', 'practice'].includes(b.taskType) ? b.taskType : 'study';
      const subjectDoc = schedulableSubjects.find((s) => s.name === b.subject);
      // eslint-disable-next-line no-await-in-loop
      await Task.create({
        user: user._id,
        subject: b.subject,
        title: TASK_TITLES[taskType](b.subject),
        date: day.date,
        durationMinutes: b.minutes,
        priority: subjectDoc ? subjectDoc.priority : 3,
        source: 'ai',
        autoGenerated: true,
        type: taskType,
        subjectId: subjectDoc ? subjectDoc._id : null,
      });
      created += 1;
    }
  }

  // 3) Recompute + persist live metrics for every subject (including locked
  //    ones, so their dashboard numbers stay accurate even though their
  //    tasks weren't touched).
  const metrics = computePlannerMetrics(user, allSubjects);
  const deadlineWarnings = [];
  const now = new Date();
  await Promise.all(
    allSubjects.map((s) => {
      const m = metrics[String(s._id)];
      if (!m) return Promise.resolve();
      s.expectedCompletionDate = m.expectedCompletionDate;
      s.requiredDailyHours = m.requiredDailyHours;
      s.deadlineRiskScore = m.deadlineRiskScore;
      s.forecastStatus = m.status;
      s.lastRescheduledAt = now;
      if (m.warning) deadlineWarnings.push({ subject: s.name, warning: m.warning, suggestions: m.suggestions });
      return s.save();
    })
  );

  return {
    removed: removeResult.deletedCount || 0,
    created,
    deadlineWarnings,
    subjects: allSubjects,
  };
}

module.exports = { regenerateFutureSchedule };
