const Task = require('../models/Task');
const { minutesToTime, timeToMinutes } = require('./scheduleValidation');

const DAY_MS = 24 * 60 * 60 * 1000;
const DEFAULT_WEEKS_AHEAD = 8; // how far ahead to generate recurring sessions

/** Returns the later of (examDate) or (today + DEFAULT_WEEKS_AHEAD weeks), capped so we don't generate forever. */
function horizonDate(examDate) {
  const fallback = new Date(Date.now() + DEFAULT_WEEKS_AHEAD * 7 * DAY_MS);
  if (!examDate) return fallback;
  const exam = new Date(examDate);
  return exam < fallback ? exam : fallback;
}

/**
 * (Re)generates Task documents of type 'revision' for a RevisionPlan.
 * Deletes previously auto-generated, not-yet-completed sessions for this
 * plan first, so edits to the plan are reflected going forward without
 * duplicating or touching sessions the user already completed.
 */
async function generateRevisionSessions(userId, plan, examDate) {
  await Task.deleteMany({
    user: userId,
    revisionPlanId: plan._id,
    completed: false,
    date: { $gte: new Date(new Date().setHours(0, 0, 0, 0)) },
  });

  if (!plan.active || !plan.daysOfWeek.length) return [];

  const start = new Date();
  start.setHours(0, 0, 0, 0);
  const end = horizonDate(examDate);

  const startMinutes = timeToMinutes(plan.startTime) ?? 0;
  const created = [];

  for (let d = new Date(start); d <= end; d.setDate(d.getDate() + 1)) {
    if (!plan.daysOfWeek.includes(d.getDay())) continue;

    const sessionDate = new Date(d);
    const endMinutes = startMinutes + plan.durationMinutes;

    // eslint-disable-next-line no-await-in-loop
    const task = await Task.create({
      user: userId,
      subject: plan.subject,
      title: `Revise ${plan.subject}`,
      date: sessionDate,
      startTime: minutesToTime(startMinutes),
      endTime: minutesToTime(endMinutes),
      durationMinutes: plan.durationMinutes,
      type: 'revision',
      source: 'ai',
      autoGenerated: true,
      revisionPlanId: plan._id,
    });
    created.push(task);
  }

  return created;
}

/**
 * (Re)generates Task documents of type 'mock_exam' for a MockExam entry.
 * If repeatWeekly is false, creates a single session on the given date.
 */
async function generateMockExamSessions(userId, mockExam, examDate) {
  await Task.deleteMany({
    user: userId,
    mockExamId: mockExam._id,
    completed: false,
    date: { $gte: new Date(new Date().setHours(0, 0, 0, 0)) },
  });

  if (!mockExam.active) return [];

  const startMinutes = timeToMinutes(mockExam.startTime) ?? 0;
  const endMinutes = startMinutes + mockExam.durationMinutes;
  const title = mockExam.title || `${mockExam.subject} Mock Exam`;
  const created = [];

  const makeSession = async (sessionDate) => {
    const task = await Task.create({
      user: userId,
      subject: mockExam.subject,
      title,
      date: sessionDate,
      startTime: minutesToTime(startMinutes),
      endTime: minutesToTime(endMinutes),
      durationMinutes: mockExam.durationMinutes,
      type: 'mock_exam',
      source: 'ai',
      autoGenerated: true,
      mockExamId: mockExam._id,
    });
    created.push(task);
  };

  if (!mockExam.repeatWeekly) {
    if (mockExam.date) await makeSession(new Date(mockExam.date));
    return created;
  }

  const start = new Date();
  start.setHours(0, 0, 0, 0);
  const end = horizonDate(examDate);

  for (let d = new Date(start); d <= end; d.setDate(d.getDate() + 1)) {
    if (d.getDay() !== mockExam.dayOfWeek) continue;
    // eslint-disable-next-line no-await-in-loop
    await makeSession(new Date(d));
  }

  return created;
}

module.exports = { generateRevisionSessions, generateMockExamSessions };
